spring.application.name=Silent Isolation


spring.datasource.url=jdbc:postgresql://localhost:5432/Silo Db
spring.datasource.username=postgres
spring.datasource.password=mshah
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
